# Generated by Django 2.2.3 on 2019-07-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBookLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_email', models.CharField(max_length=30)),
                ('log_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FBookSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_first', models.CharField(max_length=30)),
                ('sign_last', models.CharField(max_length=30)),
                ('sign_email', models.CharField(max_length=30)),
                ('sign_password', models.CharField(max_length=30)),
                ('sign_day', models.CharField(max_length=30)),
                ('sign_month', models.CharField(max_length=30)),
                ('sign_year', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='FBook',
        ),
    ]
